### PR TITLE
Improved: code to use defined method instead of writing same code again(#456)

### LINKED ISSUE #456: Using defined method instead of writing the same code again
## Current behavior
In payment.ts file (https://github.com/vuestorefront/vue-storefront/blob/master/core/modules/checkout/components/Payment.ts#L107), we have used if conditions to check for `billingData` but we already have a method defined (https://github.com/vuestorefront/vue-storefront/blob/master/core/modules/checkout/components/Payment.ts#L97) which does the same work for us. So we can call that method instead of writing the same condition again.

## Expected behavior
Should make a method call instead of writing the same code again

## Version of Vue Storefront

- [x] Vue Storefront
- [ ] Vue Storefront Next

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

### PR DESCRIPTION
**Pull request by ymaheshwari1**
### Related Issues
Using the same logic again to check for default_billing

closes #456 

### Short Description of the PR

Used the predefined method instead of writing the conditions again

### Pull Request Checklist

- [x] I have updated the Changelog ([V1](https://github.com/vuestorefront/vue-storefront-1/blob/master/CHANGELOG.md)) and mentioned all breaking changes in the public API.
- [ ] I have documented all new public APIs and made changes to existing docs mentioning the parts I've changed so they're up to date.
- [x] I have tested my Pull Request on production build and (to my knowledge) it works without any issues

- [ ] I have followed [naming conventions](https://github.com/kettanaito/naming-cheatsheet)

### Upgrade Notes and Changelog
- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [x] I've updated the [Upgrade notes](https://github.com/vuestorefront/vue-storefront-1/blob/master/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/vuestorefront/vue-storefront-1/blob/master/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/vuestorefront/vue-storefront-1/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by ymaheshwari1** [comment]
@Fifciu Please review

**Review by Fifciu — CHANGES_REQUESTED** [review]
Good idea, thanks.
Please solve the conflict in the changelog

**Comment by ymaheshwari1** [comment]
> Good idea, thanks. Please solve the conflict in the changelog

Resolved conflicts

**Review by Fifciu — CHANGES_REQUESTED** [review]
I see unit tests are not passing. Could you please fix them @ymaheshwari1 ?

**Comment by ymaheshwari1** [comment]
> I see unit tests are not passing. Could you please fix them @ymaheshwari1 ?

Sure

**Comment by ymaheshwari1** [comment]
> I see unit tests are not passing. Could you please fix them @ymaheshwari1 ?

Hi @Fifciu Fixed the failing unit tests, please review

**Comment by Fifciu** [comment]
Great job @ymaheshwari1 , thank you a lot!

**Review by Fifciu — APPROVED** [review]

**Pull request merged**
